In [1]:
# !pip install imutils
# !pip install dlib

import collections
from collections import OrderedDict
from imutils import face_utils
import numpy as np
import argparse
import imutils
import dlib
import cv2

FACIAL_LANDMARKS_IDXS = OrderedDict([
    ("mouth", (48, 68)),
    ('inner_mouth', (60, 68)),
    ("right_eyebrow", (17, 22)),
    ("left_eyebrow", (22, 27)),
    ("right_eye", (36, 42)),
    ("left_eye", (42, 48)),
    ("nose", (27, 35)),
    ("jaw", (0, 17))
])

from google.colab import drive
drive.mount('/content/gdrive/')

detector = dlib.get_frontal_face_detector()
predictor = dlib.shape_predictor('/content/gdrive/MyDrive/personality_datasets/shape_predictor_68_face_landmarks.dat')


Mounted at /content/gdrive/


In [2]:
import os
import cv2
# compiled_stacked_coors = []
# for file1 in os.listdir('/content/gdrive/MyDrive/personality_datasets/train_nose/big_nose/'):
#     print('Train Nose Big Nose', file1)
#     image = cv2.imread('/content/gdrive/MyDrive/personality_datasets/train_nose/big_nose/'+file1)
#     # image = imutils.resize(image, width=1500, height=1500)
#     gray = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)
#     # detect faces in the grayscale image
#     rects = detector(gray, 1)
#     stacked_coors = []
#     for (index, rect) in enumerate(rects):
#         shape = predictor(gray, rect)
#         shape = face_utils.shape_to_np(shape)

#         a_dict = face_utils.FACIAL_LANDMARKS_IDXS.items()
#         tuple_list = list(a_dict)
#         print(tuple_list)
#         tuple_list = [tuple_list[6]]
#         for f in range(len(tuple_list)):
#             key_value = tuple_list[f]
#             name = key_value[0]

#             i = key_value[1][0]
#             j = key_value[1][1]

#             for (x, y) in shape[i:j]:
#                 stacked_coors.append((x,y))
#     compiled_stacked_coors.append([stacked_coors, 0])
    

# for file1 in os.listdir('/content/gdrive/MyDrive/personality_datasets/train_nose/no_big_nose/'):
#     print('Train Nose No Big Nose', file1)
#     image = cv2.imread('/content/gdrive/MyDrive/personality_datasets/train_nose/no_big_nose/'+file1)
#     # image = imutils.resize(image, width=1500, height=1500)
#     gray = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)
#     # detect faces in the grayscale image
#     rects = detector(gray, 1)
#     stacked_coors = []
#     for (index, rect) in enumerate(rects):
#         shape = predictor(gray, rect)
#         shape = face_utils.shape_to_np(shape)

#         a_dict = face_utils.FACIAL_LANDMARKS_IDXS.items()
#         tuple_list = list(a_dict)

#         tuple_list = [tuple_list[6]]
#         for f in range(len(tuple_list)):
#             key_value = tuple_list[f]
#             name = key_value[0]

#             i = key_value[1][0]
#             j = key_value[1][1]

#             for (x, y) in shape[i:j]:
#                 stacked_coors.append((x,y))
#     compiled_stacked_coors.append([stacked_coors, 1])

# for file1 in os.listdir('/content/gdrive/MyDrive/personality_datasets/valid_nose/big_nose/'):
#     print('Valid Nose Big Nose', file1)
#     image = cv2.imread('/content/gdrive/MyDrive/personality_datasets/valid_nose/big_nose/'+file1)
#     # image = imutils.resize(image, width=1500, height=1500)
#     gray = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)
#     # detect faces in the grayscale image
#     rects = detector(gray, 1)
#     stacked_coors = []
#     for (index, rect) in enumerate(rects):
#         shape = predictor(gray, rect)
#         shape = face_utils.shape_to_np(shape)

#         a_dict = face_utils.FACIAL_LANDMARKS_IDXS.items()
#         tuple_list = list(a_dict)
#         tuple_list = [tuple_list[6]]
#         for f in range(len(tuple_list)):
#             key_value = tuple_list[f]
#             name = key_value[0]

#             i = key_value[1][0]
#             j = key_value[1][1]

#             for (x, y) in shape[i:j]:
#                 stacked_coors.append((x,y))
#     compiled_stacked_coors.append([stacked_coors, 0])
    

# for file1 in os.listdir('/content/gdrive/MyDrive/personality_datasets/valid_nose/no_big_nose/'):
#     print('Valid Nose No Big Nose', file1)
#     image = cv2.imread('/content/gdrive/MyDrive/personality_datasets/valid_nose/no_big_nose/'+file1)
#     # image = imutils.resize(image, width=1500, height=1500)
#     gray = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)
#     # detect faces in the grayscale image
#     rects = detector(gray, 1)
#     stacked_coors = []
#     for (index, rect) in enumerate(rects):
#         shape = predictor(gray, rect)
#         shape = face_utils.shape_to_np(shape)

#         a_dict = face_utils.FACIAL_LANDMARKS_IDXS.items()
#         tuple_list = list(a_dict)
#         tuple_list = [tuple_list[6]]
#         for f in range(len(tuple_list)):
#             key_value = tuple_list[f]
#             name = key_value[0]

#             i = key_value[1][0]
#             j = key_value[1][1]

#             for (x, y) in shape[i:j]:
#                 stacked_coors.append((x,y))
#     compiled_stacked_coors.append([stacked_coors, 1])

In [3]:
import pandas as pd
# index = 0
# dictionary = {}
# for i in range(len(compiled_stacked_coors)):
#   dictionary[str(index)] = compiled_stacked_coors[i]
#   index += 1
# df = pd.DataFrame (data = dictionary)
# df.to_csv('/content/gdrive/MyDrive/personality_datasets/compiled_stacked_coors.csv')

In [4]:
data = pd.read_csv('/content/gdrive/MyDrive/personality_datasets/compiled_stacked_coors.csv')
data = data.to_dict()
data

{'Unnamed: 0': {0: 0, 1: 1},
 '0': {0: '[(87, 110), (86, 117), (85, 125), (85, 133), (79, 139), (82, 140), (86, 141), (90, 140), (94, 140)]',
  1: '1'},
 '1': {0: '[(89, 110), (90, 116), (90, 123), (90, 130), (82, 136), (86, 138), (90, 139), (93, 138), (97, 137)]',
  1: '1'},
 '2': {0: '[(89, 114), (89, 123), (89, 132), (89, 141), (80, 143), (85, 145), (89, 147), (94, 145), (98, 143)]',
  1: '1'},
 '3': {0: '[(88, 110), (87, 117), (86, 123), (85, 130), (80, 137), (83, 138), (86, 140), (90, 139), (94, 137)]',
  1: '1'},
 '4': {0: '[(89, 112), (90, 120), (90, 127), (91, 135), (83, 140), (86, 142), (90, 144), (94, 142), (97, 140)]',
  1: '1'},
 '5': {0: '[(84, 110), (83, 116), (82, 122), (80, 129), (77, 136), (80, 137), (83, 138), (87, 137), (91, 136)]',
  1: '1'},
 '6': {0: '[(86, 113), (86, 122), (86, 130), (86, 139), (80, 142), (83, 143), (87, 145), (91, 143), (95, 141)]',
  1: '1'},
 '7': {0: '[(88, 109), (88, 115), (87, 121), (87, 128), (77, 136), (82, 137), (88, 138), (93, 136), (99

In [47]:
import pandas as pd
from google.colab import drive
df = pd.read_csv('/content/gdrive/MyDrive/personality_datasets/compiled_stacked_coors.csv')
df = df.T

# dictionary = df.to_dict()
# compiled_stacked_coors = []

# for i in range(0, 13669):
#   string = dictionary[0][str(i)]
#   index_value = dictionary[1][str(i)]

#   split_string = string.split(', (')
#   split_string[0] = split_string[0][2:]
#   split_string[len(split_string)-1] = split_string[len(split_string)-1][:-1]

#   not_paranthesis = True
#   for i in range(len(split_string)):
#     split_string[i] = '(' + split_string[i]
#     string = split_string[i]
#     string = string.split(', ')
#     # print(string)
#     if (string[0] == '('):
#       not_paranthesis = False
#       continue
#     string[0] = string[0][1:]
#     string[1] = string[1][:-1]
#     if (not string[0].isnumeric() or not string[1].isnumeric() or not index_value.isnumeric()):
#       print("HERE")
#       not_paranthesis = False
#     string = [int(string[0]), int(string[1])]
#     split_string[i] = string

#   if (not_paranthesis):
#     # print([split_string, index_value])
#     compiled_stacked_coors.append([split_string, int(index_value)])

dictionary = df.to_dict()
compiled_stacked_coors = []
compiled_stacked_coors_values = []

for i in range(0, len(df)-1):
  string = dictionary[0][str(i)]
  index_value = dictionary[1][str(i)]

  print(string + " " + index_value)

  split_string = string.split(', (')
  split_string[0] = split_string[0][2:]
  split_string[len(split_string)-1] = split_string[len(split_string)-1][:-1]

  not_paranthesis = True
  new_string = []
  for i in range(len(split_string)):
    split_string[i] = '(' + split_string[i]
    string = split_string[i]
    string = string.split(', ')
    # print(string)
    if (string[0] == '('):
      not_paranthesis = False
      continue
    string[0] = string[0][1:]
    string[1] = string[1][:-1]
    if (not string[0].isnumeric() or not string[1].isnumeric() or not index_value.isnumeric()):
      not_paranthesis = False
    new_string.append([int(string[0])/150.0, int(string[1])/150.0])

  if (not_paranthesis):
    # print([split_string, index_value])
    if (len(new_string) == 9):
      compiled_stacked_coors.append(new_string)
      compiled_stacked_coors_values.append(int(index_value))
# print(dictionary[0]['0'])

# string = '[(95, 113), (96, 121), (98, 129), (100, 138), (87, 143), (91, 144), (95, 144), (99, 143), (102, 141)]'
# split_string = string.split(', (')
# split_string[0] = split_string[0][2:]
# split_string[len(split_string)-1] = split_string[len(split_string)-1][:-1]

# for i in range(len(split_string)):
#   split_string[i] = '(' + split_string[i]
# split_string


Streaming output truncated to the last 5000 lines.
[(90, 112), (90, 120), (91, 128), (91, 137), (81, 140), (86, 141), (91, 143), (96, 141), (100, 139)] 0
[(88, 113), (87, 121), (87, 130), (87, 138), (78, 142), (83, 143), (87, 145), (92, 143), (97, 142)] 0
[(89, 111), (89, 119), (89, 127), (89, 136), (81, 140), (85, 142), (89, 144), (93, 142), (97, 141)] 0
[(93, 111), (94, 117), (95, 123), (96, 128), (86, 136), (90, 137), (94, 138), (97, 137), (100, 136)] 0
[(93, 109), (95, 114), (98, 119), (101, 124), (87, 134), (92, 135), (96, 136), (99, 135), (101, 135)] 0
[(91, 110), (92, 117), (93, 124), (94, 131), (83, 137), (88, 138), (92, 139), (96, 138), (99, 137)] 0
[(90, 112), (91, 120), (91, 129), (91, 137), (82, 140), (86, 142), (91, 144), (95, 142), (99, 140)] 0
[(94, 112), (95, 121), (96, 129), (97, 138), (85, 141), (90, 143), (95, 145), (99, 144), (102, 141)] 0
[(85, 112), (84, 120), (82, 127), (81, 136), (75, 140), (79, 142), (83, 144), (89, 142), (94, 141)] 0
[(95, 113), (95, 121), (96

In [59]:
import tensorflow as tf
from random import random
import random

c = list(zip(compiled_stacked_coors, compiled_stacked_coors_values))
random.shuffle(c)
compiled_stacked_coors, compiled_stacked_coors_values = zip(*c)

count, count2 = 0, 0
for i in compiled_stacked_coors_values:
  if (i == 1):
    count += 1
  elif (i == 0):
    count2 += 1
  else:
    print("ERROR")

print(count)
print(count2)


# new_compiled_stacked_coors_values = []
# new_compiled_stacked_coors = []

# count = 0
# for i in range(len(compiled_stacked_coors_values)):
#   if 0 == compiled_stacked_coors_values[i]:
#     new_compiled_stacked_coors.append(compiled_stacked_coors[i])
#     new_compiled_stacked_coors_values.append(compiled_stacked_coors_values[i])
#   else:
#     if (count > 3977):
#       continue
#     else:
#       count += 1
#     new_compiled_stacked_coors.append(compiled_stacked_coors[i])
#     new_compiled_stacked_coors_values.append(compiled_stacked_coors_values[i])

# compiled_stacked_coors = new_compiled_stacked_coors
# compiled_stacked_coors_values = new_compiled_stacked_coors_values

train = compiled_stacked_coors[:int(0.6*len(compiled_stacked_coors))]
train_values = compiled_stacked_coors_values[:int(0.6*len(compiled_stacked_coors_values))]
valid = compiled_stacked_coors[int(0.6*len(compiled_stacked_coors)):]
valid_values = compiled_stacked_coors_values[int(0.6*len(compiled_stacked_coors_values)):]
# # import pandas as pd
# # index = 0
# # dictionary = {}
# # for i in range(len(compiled_stacked_coors)):
# #   dictionary[str(index)] = compiled_stacked_coors[i]
# # df = pd.DataFrame (data = dictionary)
# # df.to_csv('/content/gdrive/MyDrive/personality_datasets/compiled_stacked_coors.csv')
# # train_coor = []
# # for coordinate in train:
# #     l = []
# #     for val in coordinate:
# #         set_val = []
# #         if (len(val) > 1):
# #             for item in val:

# #                 set_val.append(val)
# #             l.append(set_val)
# #         else:
# #             l.append(val)
# #     train_coor.append(l)
# # val_coor = []
# # for coordinate in valid:
# #     l = []
# #     for val in coordinate:
# #         set_val = []
# #         if (len(val) > 1):
# #             for item in val:
# #                 set_val.append(val)
# #             l.append(set_val)
# #         else:
# #             l.append(val)
# #     val_coor.append(l)

# # train = tf.ragged.constant(train)
# # val_coor = tf.ragged.constant(val_coor)

# print(len(valid))
# print(len(valid_values))
# # print(train_values)
# # print(valid)

train_values = tf.one_hot(train_values, depth = 2)
valid_values = tf.one_hot(valid_values, depth = 2)

train_dataset = tf.data.Dataset.from_tensor_slices((list(train), train_values)).shuffle(len(train_values)).batch(64)
val_dataset = tf.data.Dataset.from_tensor_slices((list(valid), valid_values)).shuffle(len(valid_values)).batch(64)
print(train_dataset)
# print(train_dataset.batch(32))

5472
5639
<BatchDataset shapes: ((None, 9, 2), (None, 2)), types: (tf.float32, tf.float32)>


In [67]:
import keras
model = keras.Sequential([
    keras.layers.Reshape(target_shape=(18*1,), input_shape=(9,2)),
    keras.layers.Dense(units=128, activation='sigmoid'),
    keras.layers.Dense(units=64, activation='sigmoid'),
    keras.layers.Dense(units=32, activation='sigmoid'),
    keras.layers.Dense(units=10, activation='sigmoid'),
    keras.layers.Dense(units=2, activation='sigmoid')
])

In [68]:
model.compile(optimizer=tf.optimizers.Adam(learning_rate=0.01), 
              loss=tf.losses.BinaryCrossentropy(from_logits=True),
              metrics=['accuracy'])

history = model.fit(
    train_dataset.repeat(), 
    epochs=10, 
    steps_per_epoch=500,
    batch_size = 32,
    validation_data=val_dataset.repeat(), 
    validation_steps = 2
)

Epoch 1/10
500/500 [==============================] - 2s 2ms/step - loss: 0.6972 - accuracy: 0.4948 - val_loss: 0.6944 - val_accuracy: 0.4922
Epoch 2/10
500/500 [==============================] - 1s 2ms/step - loss: 0.6933 - accuracy: 0.5030 - val_loss: 0.6934 - val_accuracy: 0.4609
Epoch 3/10
500/500 [==============================] - 1s 2ms/step - loss: 0.6932 - accuracy: 0.5035 - val_loss: 0.6929 - val_accuracy: 0.5391
Epoch 4/10
500/500 [==============================] - 1s 2ms/step - loss: 0.6932 - accuracy: 0.5035 - val_loss: 0.6927 - val_accuracy: 0.5234
Epoch 5/10
500/500 [==============================] - 1s 2ms/step - loss: 0.6932 - accuracy: 0.5041 - val_loss: 0.6914 - val_accuracy: 0.5781
Epoch 6/10
500/500 [==============================] - 1s 2ms/step - loss: 0.6933 - accuracy: 0.5045 - val_loss: 0.6936 - val_accuracy: 0.4375
Epoch 7/10
500/500 [==============================] - 1s 2ms/step - loss: 0.6932 - accuracy: 0.5015 - val_loss: 0.6925 - val_accuracy: 0.5234
Epoch 

In [ ]:
import pandas as pd
df = pd.read_csv('coordinate.csv')
coordinates = df['coordinates']
expanded_coor = []
for coordinate in coordinates:
    for val in coordinate:
        expanded_coor.append(val)
dataset = tf.data.Dataset.from_tensor_slices(expanded_coor)

In [ ]:
a_dict = face_utils.FACIAL_LANDMARKS_IDXS.items()
tuple_list = list(a_dict)

tuple_list = tuple_list[4] + tuple_list[5]
tuple_list

('right_eye', (36, 42), 'left_eye', (42, 48))

In [ ]:
('he', (1, 2))[1][1]

2

In [ ]:
string = '(91, 113)'
string = string.split(', ')
string[0] = string[0][1:]
string[1] = string[1][:-1]
# print(string)
string = (int(string[0]), int(string[1]))
# print(string)

['91', '113']
(91, 113)


In [ ]:
print(len(os.listdir('/content/gdrive/MyDrive/personality_datasets/train_images/')))

OSError: ignored

In [ ]:
len(data)

49582

In [51]:
import tensorflow as tf
from tensorflow import keras

(x_train, y_train), (x_val, y_val) = keras.datasets.fashion_mnist.load_data()

In [38]:
y_train = tf.one_hot(y_train, depth = 10)
train_dataset = tf.data.Dataset.from_tensor_slices((x_train,y_train))
print(train_dataset)

<TensorSliceDataset shapes: ((28, 28), (10,)), types: (tf.uint8, tf.float32)>


In [52]:
print(x_train)

[[[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 [[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 [[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 ...

 [[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 [[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 [[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]]


In [53]:
print(train)

([[0.6, 0.7533333333333333], [0.6, 0.8066666666666666], [0.6, 0.86], [0.6, 0.9133333333333333], [0.5466666666666666, 0.94], [0.5733333333333334, 0.9466666666666667], [0.6, 0.96], [0.6266666666666667, 0.9533333333333334], [0.6466666666666666, 0.94]], [[0.6133333333333333, 0.7466666666666667], [0.6133333333333333, 0.8], [0.6266666666666667, 0.8533333333333334], [0.6333333333333333, 0.9066666666666666], [0.5533333333333333, 0.94], [0.5866666666666667, 0.9466666666666667], [0.62, 0.96], [0.6533333333333333, 0.9466666666666667], [0.6733333333333333, 0.9333333333333333]], [[0.5666666666666667, 0.76], [0.5666666666666667, 0.8], [0.56, 0.8533333333333334], [0.56, 0.9], [0.5266666666666666, 0.9266666666666666], [0.5466666666666666, 0.9333333333333333], [0.5666666666666667, 0.94], [0.5933333333333334, 0.9333333333333333], [0.62, 0.9266666666666666]], [[0.5666666666666667, 0.7466666666666667], [0.56, 0.8], [0.5533333333333333, 0.86], [0.5466666666666666, 0.9133333333333333], [0.52, 0.94], [0.54, 